Algoritmo "Creuza_ano"

Var
   ano_nas,ano_atual, idd : inteiro
Inicio
   escreval("Emque ano nós estamos ?")
   leia(ano_atual)
   escreval("Em que ano eu nasci ?")
   leia(ano_nas)
   limpatela
   idd <- ano_atual - ano_nas
   escreval("========================")
   escreval("  ")
   escreval("Creuza, sua idade é",idd," anos.")
   escreval("  ")
   escreval("========================")
Fimalgoritmo